version: '3'

services:
  # Plex - Media Server
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/media-server/tv:/tv
      - /volume1/media-server/movies:/movies
    restart: unless-stopped

  # Sonarr - TV Shows Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/media-server:/data
    ports:
      - 51001:8989
    restart: unless-stopped

  # Radarr - Movies Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/media-server:/data
    ports:
      - 51002:7878
    restart: unless-stopped
  
  # Prowlarr - Indexer Manager (replaces Jackett)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 51003:9696
    restart: unless-stopped

  # qBittorrent - Download Client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/media-server/downloads:/downloads
    ports:
      - 51004:8080
      - 51005:6881
      - 51005:6881/udp
    restart: unless-stopped

  # Bazarr - Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume1/media-server/movies:/movies
      - /volume1/media-server/tv:/tv
    ports:
      - 51006:6767
    restart: unless-stopped

  # Overseerr - Request Management
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/overseerr:/config
    ports:
      - 51007:5055
    restart: unless-stopped

  # Homarr - Dashboard
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/homarr/configs:/app/data/configs
      - /volume1/docker/homarr/icons:/app/public/icons
      - /volume1/docker/homarr/data:/data
    ports:
      - 51000:7575
    restart: unless-stopped

  # Flaresolverr - Helps with CAPTCHA challenges
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Etc/UTC
      - CAPTCHA_SOLVER=none
    ports:
      - 51008:8191
    restart: unless-stopped

  # Watchtower - Auto-updates your containers
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=Etc/UTC
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Runs at 4 AM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  plex:
  sonarr:
  radarr:
  prowlarr:
  qbittorrent:
  bazarr:
  overseerr:
  homarr:
